settings:
  report-author:
    name: "Jan Novák"
    email: test@example.com
    company:
    phoneNumber: ccd
  sftpDirectory: /sftp_user
  minTimeDiff: 500  # minimal time difference (in minutes) between 2 consecutive crawling of the same URL
  requireEmailConfirmation: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: sa
    password: password
  exposed:
    show-sql: true