settings:
  timeLimit: 50   #time limit in hours
  downloaderConfig:
    filePath: testPath
    firefoxProfilePath: /home/jirik/snap/firefox/common/.mozilla/firefox/53qm6ryg.TestProfile

remoteStorage:
  address: localhost
  port: 22
  path: /path/to/directory